<?php

function game_page_alter($page) {
  $notice = '<div>&copy; 2007 - 2010 Akshay Joshi and Nikhil Mahajan. All Rights Reserved.</div>';
  $page['footer']['main'] = array('#markup' => $notice);
}

/**
 * Implements hook_user_login().
 */
function game_user_login(&$edit, $account) {
  drupal_goto('game');
}

function game_library() {
  return array(
    'css_reset' => array(
      'title' => 'CSS Reset',
      'website' => 'http://meyerweb.com/eric/tools/css/reset/',
      'version' => '1.0',
      'css' => array(
        drupal_get_path('module', 'game') . '/reset.css' => array(
          'type' => 'file',
          'media' => 'screen',
        ),
      ),
    ),
  );
}

